// Code generated by protoc-gen-go-http. DO NOT EDIT.

package v1

import (
	context "context"
	middleware "github.com/go-kratos/kratos/v2/middleware"
	http1 "github.com/go-kratos/kratos/v2/transport/http"
	http "net/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
// context./http./middleware.
const _ = http1.SupportPackageIsVersion1

type PostHTTPServer interface {
	CreatePost(context.Context, *CreatePostRequest) (*CreatePostReply, error)

	DeletePost(context.Context, *DeletePostRequest) (*DeletePostReply, error)

	GetPost(context.Context, *GetPostRequest) (*GetPostReply, error)

	ListPost(context.Context, *ListPostRequest) (*ListPostReply, error)

	UpdatePost(context.Context, *UpdatePostRequest) (*UpdatePostReply, error)
}

func RegisterPostHTTPServer(s http1.ServiceRegistrar, srv PostHTTPServer) {
	s.RegisterService(&_HTTP_Post_serviceDesc, srv)
}

func _HTTP_Post_CreatePost_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error, m middleware.Middleware) (interface{}, error) {
	var in CreatePostRequest

	if err := http1.BindQuery(req, &in); err != nil {
		return nil, err
	}

	h := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).CreatePost(ctx, &in)
	}
	out, err := m(h)(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _HTTP_Post_UpdatePost_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error, m middleware.Middleware) (interface{}, error) {
	var in UpdatePostRequest

	if err := http1.BindVars(req, &in); err != nil {
		return nil, err
	}

	if err := http1.BindQuery(req, &in); err != nil {
		return nil, err
	}

	h := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).UpdatePost(ctx, &in)
	}
	out, err := m(h)(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _HTTP_Post_DeletePost_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error, m middleware.Middleware) (interface{}, error) {
	var in DeletePostRequest

	if err := http1.BindVars(req, &in); err != nil {
		return nil, err
	}

	if err := http1.BindQuery(req, &in); err != nil {
		return nil, err
	}

	h := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).DeletePost(ctx, &in)
	}
	out, err := m(h)(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _HTTP_Post_GetPost_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error, m middleware.Middleware) (interface{}, error) {
	var in GetPostRequest

	if err := http1.BindVars(req, &in); err != nil {
		return nil, err
	}

	if err := http1.BindQuery(req, &in); err != nil {
		return nil, err
	}

	h := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).GetPost(ctx, &in)
	}
	out, err := m(h)(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _HTTP_Post_ListPost_0(srv interface{}, ctx context.Context, req *http.Request, dec func(interface{}) error, m middleware.Middleware) (interface{}, error) {
	var in ListPostRequest

	if err := http1.BindQuery(req, &in); err != nil {
		return nil, err
	}

	h := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).ListPost(ctx, &in)
	}
	out, err := m(h)(ctx, &in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _HTTP_Post_serviceDesc = http1.ServiceDesc{
	ServiceName: "api.v1.Post",
	Methods: []http1.MethodDesc{

		{
			Path:    "/v1/post/",
			Method:  "POST",
			Handler: _HTTP_Post_CreatePost_0,
		},

		{
			Path:    "/v1/post/{id}",
			Method:  "PUT",
			Handler: _HTTP_Post_UpdatePost_0,
		},

		{
			Path:    "/v1/post/{id}",
			Method:  "DELETE",
			Handler: _HTTP_Post_DeletePost_0,
		},

		{
			Path:    "/v1/post/{id}",
			Method:  "GET",
			Handler: _HTTP_Post_GetPost_0,
		},

		{
			Path:    "/v1/post/",
			Method:  "GET",
			Handler: _HTTP_Post_ListPost_0,
		},
	},
	Metadata: "api/blog/v1/post.proto",
}
