service:
  name: kratos
  version: v1.0.0
http:
  server:
    address: 0.0.0.0:8000
    timeout: 1s
grpc:
  server:
    address: 0.0.0.0:9000
    timeout: 1s
db:
  driver: mysql
  source: root:password@tcp(127.0.0.1:3306)/testdb
