// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"github.com/go-kratos/examples/blog/internal/server"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// InitApp .
func InitApp(service *Service, httpConfig *server.HTTPConfig, grpcConfig *server.GRPCConfig, logger log.Logger) (*kratos.App, error) {
	httpServer := server.NewHTTPServer(httpConfig, logger)
	grpcServer := server.NewGRPCServer(grpcConfig, logger)
	app := NewApp(service, httpServer, grpcServer, logger)
	return app, nil
}
